/* TODO: replace with real API-Football key */
import type {
  MatchWithPrediction,
  DashboardStats,
  Standing,
} from "./types";

/* TODO: replace with real API-Football key */
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalPredictions: 248,
  correctPredictions: 171,
  winRate: 68.9,
  avgOdds: 1.84,
  roi: 12.4,
  streak: 5,
};

/* TODO: replace with real API-Football key */
export const MOCK_MATCHES: MatchWithPrediction[] = [
  {
    id: 1001,
    date: "2026-06-18T20:45:00+00:00",
    venue: "Parc des Princes, Paris",
    status: "NS",
    homeTeam: {
      id: 85,
      name: "Paris Saint-Germain",
      logo: "https://media.api-sports.io/football/teams/85.png",
      country: "France",
    },
    awayTeam: {
      id: 80,
      name: "Lyon",
      logo: "https://media.api-sports.io/football/teams/80.png",
      country: "France",
    },
    league: {
      id: 61,
      name: "Ligue 1",
      country: "France",
      logo: "https://media.api-sports.io/football/leagues/61.png",
      flag: "https://media.api-sports.io/flags/fr.svg",
      season: 2025,
      round: "Journée 34",
    },
    score: { home: null, away: null },
    prediction: {
      fixtureId: 1001,
      winner: "home",
      confidence: 78,
      advice: "Paris Saint-Germain à domicile",
      goals: { home: "2.1", away: "0.8" },
      percent: { home: "78%", draw: "14%", away: "8%" },
    },
    odds: {
      fixtureId: 1001,
      bookmaker: "Bet365",
      home: 1.45,
      draw: 4.20,
      away: 7.50,
    },
    homeForm: [
      { result: "W", homeOrAway: "H", opponent: "Marseille", score: "3-1", date: "2026-06-11" },
      { result: "W", homeOrAway: "A", opponent: "Monaco", score: "2-0", date: "2026-06-04" },
      { result: "W", homeOrAway: "H", opponent: "Rennes", score: "4-2", date: "2026-05-28" },
      { result: "D", homeOrAway: "A", opponent: "Lens", score: "1-1", date: "2026-05-21" },
      { result: "W", homeOrAway: "H", opponent: "Nice", score: "2-0", date: "2026-05-14" },
    ],
    awayForm: [
      { result: "L", homeOrAway: "H", opponent: "Monaco", score: "0-2", date: "2026-06-11" },
      { result: "W", homeOrAway: "A", opponent: "Nantes", score: "1-0", date: "2026-06-04" },
      { result: "D", homeOrAway: "H", opponent: "Rennes", score: "2-2", date: "2026-05-28" },
      { result: "L", homeOrAway: "A", opponent: "Lens", score: "1-3", date: "2026-05-21" },
      { result: "W", homeOrAway: "H", opponent: "Strasbourg", score: "2-1", date: "2026-05-14" },
    ],
  },
  {
    id: 1002,
    date: "2026-06-18T17:00:00+00:00",
    venue: "Allianz Arena, Munich",
    status: "NS",
    homeTeam: {
      id: 157,
      name: "Bayern Munich",
      logo: "https://media.api-sports.io/football/teams/157.png",
      country: "Germany",
    },
    awayTeam: {
      id: 165,
      name: "Borussia Dortmund",
      logo: "https://media.api-sports.io/football/teams/165.png",
      country: "Germany",
    },
    league: {
      id: 78,
      name: "Bundesliga",
      country: "Germany",
      logo: "https://media.api-sports.io/football/leagues/78.png",
      flag: "https://media.api-sports.io/flags/de.svg",
      season: 2025,
      round: "Journée 30",
    },
    score: { home: null, away: null },
    prediction: {
      fixtureId: 1002,
      winner: "home",
      confidence: 65,
      advice: "Bayern Munich favori à domicile",
      goals: { home: "2.4", away: "1.2" },
      percent: { home: "65%", draw: "18%", away: "17%" },
    },
    odds: {
      fixtureId: 1002,
      bookmaker: "Bet365",
      home: 1.75,
      draw: 3.80,
      away: 4.50,
    },
    homeForm: [
      { result: "W", homeOrAway: "H", opponent: "Leipzig", score: "3-0", date: "2026-06-11" },
      { result: "W", homeOrAway: "A", opponent: "Wolfsburg", score: "2-1", date: "2026-06-04" },
      { result: "W", homeOrAway: "H", opponent: "Frankfurt", score: "5-1", date: "2026-05-28" },
      { result: "W", homeOrAway: "A", opponent: "Bremen", score: "2-0", date: "2026-05-21" },
      { result: "D", homeOrAway: "H", opponent: "Leverkusen", score: "2-2", date: "2026-05-14" },
    ],
    awayForm: [
      { result: "W", homeOrAway: "A", opponent: "Stuttgart", score: "2-0", date: "2026-06-11" },
      { result: "D", homeOrAway: "H", opponent: "Leipzig", score: "1-1", date: "2026-06-04" },
      { result: "W", homeOrAway: "A", opponent: "Bremen", score: "3-1", date: "2026-05-28" },
      { result: "L", homeOrAway: "H", opponent: "Leverkusen", score: "0-1", date: "2026-05-21" },
      { result: "W", homeOrAway: "A", opponent: "Wolfsburg", score: "2-1", date: "2026-05-14" },
    ],
  },
  {
    id: 1003,
    date: "2026-06-19T19:45:00+00:00",
    venue: "Stamford Bridge, Londres",
    status: "NS",
    homeTeam: {
      id: 49,
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
      country: "England",
    },
    awayTeam: {
      id: 42,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
      country: "England",
    },
    league: {
      id: 39,
      name: "Premier League",
      country: "England",
      logo: "https://media.api-sports.io/football/leagues/39.png",
      flag: "https://media.api-sports.io/flags/gb.svg",
      season: 2025,
      round: "Journée 36",
    },
    score: { home: null, away: null },
    prediction: {
      fixtureId: 1003,
      winner: "draw",
      confidence: 48,
      advice: "Match serré, nul possible",
      goals: { home: "1.5", away: "1.4" },
      percent: { home: "35%", draw: "33%", away: "32%" },
    },
    odds: {
      fixtureId: 1003,
      bookmaker: "Bet365",
      home: 2.70,
      draw: 3.25,
      away: 2.65,
    },
    homeForm: [
      { result: "W", homeOrAway: "H", opponent: "Man City", score: "2-1", date: "2026-06-11" },
      { result: "L", homeOrAway: "A", opponent: "Liverpool", score: "0-2", date: "2026-06-04" },
      { result: "W", homeOrAway: "H", opponent: "Tottenham", score: "3-1", date: "2026-05-28" },
      { result: "D", homeOrAway: "A", opponent: "Newcastle", score: "1-1", date: "2026-05-21" },
      { result: "W", homeOrAway: "H", opponent: "Everton", score: "2-0", date: "2026-05-14" },
    ],
    awayForm: [
      { result: "W", homeOrAway: "A", opponent: "Tottenham", score: "2-0", date: "2026-06-11" },
      { result: "W", homeOrAway: "H", opponent: "Man United", score: "3-1", date: "2026-06-04" },
      { result: "D", homeOrAway: "A", opponent: "Man City", score: "2-2", date: "2026-05-28" },
      { result: "W", homeOrAway: "H", opponent: "West Ham", score: "2-0", date: "2026-05-21" },
      { result: "L", homeOrAway: "A", opponent: "Liverpool", score: "1-2", date: "2026-05-14" },
    ],
  },
  {
    id: 1004,
    date: "2026-06-19T21:00:00+00:00",
    venue: "Wanda Metropolitano, Madrid",
    status: "NS",
    homeTeam: {
      id: 530,
      name: "Atlético Madrid",
      logo: "https://media.api-sports.io/football/teams/530.png",
      country: "Spain",
    },
    awayTeam: {
      id: 529,
      name: "FC Barcelone",
      logo: "https://media.api-sports.io/football/teams/529.png",
      country: "Spain",
    },
    league: {
      id: 140,
      name: "La Liga",
      country: "Spain",
      logo: "https://media.api-sports.io/football/leagues/140.png",
      flag: "https://media.api-sports.io/flags/es.svg",
      season: 2025,
      round: "Journée 33",
    },
    score: { home: null, away: null },
    prediction: {
      fixtureId: 1004,
      winner: "away",
      confidence: 58,
      advice: "FC Barcelone en forme",
      goals: { home: "1.1", away: "2.0" },
      percent: { home: "25%", draw: "22%", away: "53%" },
    },
    odds: {
      fixtureId: 1004,
      bookmaker: "Bet365",
      home: 3.10,
      draw: 3.40,
      away: 2.20,
    },
    homeForm: [
      { result: "W", homeOrAway: "H", opponent: "Sevilla", score: "2-0", date: "2026-06-11" },
      { result: "D", homeOrAway: "A", opponent: "Valencia", score: "1-1", date: "2026-06-04" },
      { result: "W", homeOrAway: "H", opponent: "Getafe", score: "1-0", date: "2026-05-28" },
      { result: "L", homeOrAway: "A", opponent: "Real Madrid", score: "0-2", date: "2026-05-21" },
      { result: "W", homeOrAway: "H", opponent: "Celta", score: "3-1", date: "2026-05-14" },
    ],
    awayForm: [
      { result: "W", homeOrAway: "A", opponent: "Sevilla", score: "4-0", date: "2026-06-11" },
      { result: "W", homeOrAway: "H", opponent: "Real Madrid", score: "3-2", date: "2026-06-04" },
      { result: "W", homeOrAway: "A", opponent: "Getafe", score: "2-0", date: "2026-05-28" },
      { result: "W", homeOrAway: "H", opponent: "Valencia", score: "3-1", date: "2026-05-21" },
      { result: "D", homeOrAway: "A", opponent: "Villarreal", score: "1-1", date: "2026-05-14" },
    ],
  },
  {
    id: 1005,
    date: "2026-06-20T20:00:00+00:00",
    venue: "San Siro, Milan",
    status: "NS",
    homeTeam: {
      id: 489,
      name: "AC Milan",
      logo: "https://media.api-sports.io/football/teams/489.png",
      country: "Italy",
    },
    awayTeam: {
      id: 505,
      name: "Inter Milan",
      logo: "https://media.api-sports.io/football/teams/505.png",
      country: "Italy",
    },
    league: {
      id: 135,
      name: "Serie A",
      country: "Italy",
      logo: "https://media.api-sports.io/football/leagues/135.png",
      flag: "https://media.api-sports.io/flags/it.svg",
      season: 2025,
      round: "Journée 35",
    },
    score: { home: null, away: null },
    prediction: {
      fixtureId: 1005,
      winner: "away",
      confidence: 62,
      advice: "Inter Milan légèrement favori",
      goals: { home: "1.3", away: "1.8" },
      percent: { home: "28%", draw: "25%", away: "47%" },
    },
    odds: {
      fixtureId: 1005,
      bookmaker: "Bet365",
      home: 3.00,
      draw: 3.30,
      away: 2.40,
    },
    homeForm: [
      { result: "W", homeOrAway: "H", opponent: "Juventus", score: "2-1", date: "2026-06-11" },
      { result: "L", homeOrAway: "A", opponent: "Napoli", score: "0-3", date: "2026-06-04" },
      { result: "D", homeOrAway: "H", opponent: "Roma", score: "1-1", date: "2026-05-28" },
      { result: "W", homeOrAway: "A", opponent: "Torino", score: "2-0", date: "2026-05-21" },
      { result: "L", homeOrAway: "H", opponent: "Atalanta", score: "1-2", date: "2026-05-14" },
    ],
    awayForm: [
      { result: "W", homeOrAway: "H", opponent: "Napoli", score: "2-0", date: "2026-06-11" },
      { result: "W", homeOrAway: "A", opponent: "Juventus", score: "1-0", date: "2026-06-04" },
      { result: "W", homeOrAway: "H", opponent: "Roma", score: "3-1", date: "2026-05-28" },
      { result: "W", homeOrAway: "A", opponent: "Bologna", score: "2-1", date: "2026-05-21" },
      { result: "D", homeOrAway: "H", opponent: "Atalanta", score: "2-2", date: "2026-05-14" },
    ],
  },
];

/* TODO: replace with real API-Football key */
export const MOCK_STANDINGS: Standing[] = [
  {
    rank: 1,
    team: { id: 85, name: "Paris Saint-Germain", logo: "https://media.api-sports.io/football/teams/85.png", country: "France" },
    played: 33, won: 24, drawn: 5, lost: 4, goalsFor: 78, goalsAgainst: 32, goalsDiff: 46, points: 77, form: "WWWDW",
  },
  {
    rank: 2,
    team: { id: 91, name: "Monaco", logo: "https://media.api-sports.io/football/teams/91.png", country: "France" },
    played: 33, won: 20, drawn: 6, lost: 7, goalsFor: 65, goalsAgainst: 41, goalsDiff: 24, points: 66, form: "WDWWL",
  },
  {
    rank: 3,
    team: { id: 80, name: "Lyon", logo: "https://media.api-sports.io/football/teams/80.png", country: "France" },
    played: 33, won: 18, drawn: 7, lost: 8, goalsFor: 58, goalsAgainst: 38, goalsDiff: 20, points: 61, form: "LWDLW",
  },
  {
    rank: 4,
    team: { id: 84, name: "Nice", logo: "https://media.api-sports.io/football/teams/84.png", country: "France" },
    played: 33, won: 17, drawn: 8, lost: 8, goalsFor: 52, goalsAgainst: 40, goalsDiff: 12, points: 59, form: "WDWLD",
  },
  {
    rank: 5,
    team: { id: 81, name: "Marseille", logo: "https://media.api-sports.io/football/teams/81.png", country: "France" },
    played: 33, won: 16, drawn: 8, lost: 9, goalsFor: 55, goalsAgainst: 44, goalsDiff: 11, points: 56, form: "LWWWD",
  },
];

